<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InitialDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        DB::table('users')->upsert([
            [
                'id' => 1,
                'name' => 'Phạm Trọng Tính',
                'email' => 'test@gmail.com',
                'password' => '$2y$12$XUotYdbEzpfa5/2E0/z6wezJ3EA3B2d8Czee3CmdfsnBhGqClx3vq',
                'role' => 'admin',
                'status' => 'active',
                'created_at' => '2025-12-01 10:00:00',
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Lý Tiểu Long',
                'email' => 'longlt@tiengtrungct.vn',
                'password' => '$2y$12$XUotYdbEzpfa5/2E0/z6wezJ3EA3B2d8Czee3CmdfsnBhGqClx3vq',
                'role' => 'subadmin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Nguyễn Thị Hoa',
                'email' => 'hoant@gmail.com',
                'password' => '$2y$12$XUotYdbEzpfa5/2E0/z6wezJ3EA3B2d8Czee3CmdfsnBhGqClx3vq',
                'role' => 'user',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Vương Lực Hồng',
                'email' => 'hongvl@tiengtrungct.vn',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'subadmin',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Lê Văn Luyện',
                'email' => 'luyenlv@gmail.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'user',
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['id'], ['name', 'email', 'password', 'role', 'status', 'created_at', 'updated_at']);

        DB::table('categories')->upsert([
            [
                'category_id' => 1,
                'name' => 'Tiếng Trung Giao Tiếp',
                'slug' => 'tieng-trung-giao-tiep',
                'description' => 'Các khóa học tập trung vào kỹ năng nghe và nói thực tế.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 2,
                'name' => 'Luyện Thi HSK',
                'slug' => 'luyen-thi-hsk',
                'description' => 'Lộ trình bài bản để chinh phục chứng chỉ HSK từ 1 đến 6.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 3,
                'name' => 'Tiếng Trung Trẻ Em',
                'slug' => 'tieng-trung-tre-em',
                'description' => 'Chương trình sinh động dành cho lứa tuổi từ 6-12.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 4,
                'name' => 'Tiếng Trung Doanh Nghiệp',
                'slug' => 'tieng-trung-doanh-nghiep',
                'description' => 'Đào tạo cấp tốc cho người đi làm và kinh doanh.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => 5,
                'name' => 'Luyện Thi TOCFL',
                'slug' => 'luyen-thi-tocfl',
                'description' => 'Chứng chỉ năng lực Hán ngữ của Đài Loan.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['category_id'], ['name', 'slug', 'description', 'created_at', 'updated_at']);

        DB::table('courses')->upsert([
            [
                'course_id' => 1,
                'category_id' => 1,
                'title' => 'Tiếng Trung Sơ Cấp A1',
                'slug' => 'tieng-trung-so-cap-a1',
                'description' => 'Dành cho người mới bắt đầu.',
                'content' => 'Nội dung bao gồm phát âm Pinyin, các nét cơ bản...',
                'featured_image' => 'https://images.unsplash.com/photo-1544650039-22886fbb4323',
                'price' => 2500000,
                'status' => 'published',
                'max_students' => 15,
                'start_date' => '2026-04-01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'course_id' => 2,
                'category_id' => 2,
                'title' => 'Luyện Thi HSK 3 Cấp Tốc',
                'slug' => 'luyen-thi-hsk-3-cap-toc',
                'description' => 'Đảm bảo đầu ra HSK 3 trong 3 tháng.',
                'content' => 'Học mẹo làm bài, ôn tập 600 từ vựng cốt lõi.',
                'featured_image' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b',
                'price' => 4200000,
                'status' => 'published',
                'max_students' => 10,
                'start_date' => '2026-04-10',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'course_id' => 3,
                'category_id' => 4,
                'title' => 'Tiếng Trung Thương Mại',
                'slug' => 'tieng-trung-thuong-mai',
                'description' => 'Kỹ năng đàm phán và soạn thảo hợp đồng.',
                'content' => 'Học cách giao tiếp với đối tác Trung Quốc, từ vựng chuyên ngành.',
                'featured_image' => 'https://images.unsplash.com/photo-1552664730-d307ca884978',
                'price' => 5500000,
                'status' => 'published',
                'max_students' => 12,
                'start_date' => '2026-04-15',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'course_id' => 4,
                'category_id' => 3,
                'title' => 'Hoa Ngữ Nhí - Level 1',
                'slug' => 'hoa-ngu-nhi-level-1',
                'description' => 'Vừa học vừa chơi qua bài hát và hình ảnh.',
                'content' => 'Giúp bé làm quen với mặt chữ và âm điệu.',
                'featured_image' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7',
                'price' => 1800000,
                'status' => 'published',
                'max_students' => 10,
                'start_date' => '2026-05-01',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'course_id' => 5,
                'category_id' => 1,
                'title' => 'Giao Tiếp Thực Chiến 1-1',
                'slug' => 'giao-tiep-thuc-chien-1-1',
                'description' => 'Học trực tiếp với giáo viên bản xứ.',
                'content' => 'Chỉnh sửa phát âm cực chuẩn, phản xạ nhanh.',
                'featured_image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
                'price' => 8000000,
                'status' => 'published',
                'max_students' => 5,
                'start_date' => '2026-04-20',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['course_id'], ['category_id', 'title', 'slug', 'description', 'content', 'featured_image', 'price', 'status', 'max_students', 'start_date', 'created_at', 'updated_at']);

        DB::table('rooms')->upsert([
            [
                'room_id' => 1,
                'name' => 'Phòng A',
                'capacity' => 20,
                'location' => 'Tầng 1 - Khu A',
                'price' => 200000,
                'status' => 'available',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'room_id' => 2,
                'name' => 'Phòng B',
                'capacity' => 15,
                'location' => 'Tầng 1 - Khu B',
                'price' => 150000,
                'status' => 'available',
                'image' => 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'room_id' => 3,
                'name' => 'Phòng C',
                'capacity' => 40,
                'location' => 'Tầng 2',
                'price' => 500000,
                'status' => 'available',
                'image' => 'https://images.unsplash.com/photo-1517502884422-41eaead166d4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'room_id' => 4,
                'name' => 'Phòng D',
                'capacity' => 12,
                'location' => 'Tầng 3',
                'price' => 300000,
                'status' => 'maintenance',
                'image' => 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'room_id' => 5,
                'name' => 'Phòng E',
                'capacity' => 6,
                'location' => 'Lầu 4',
                'price' => 400000,
                'status' => 'available',
                'image' => 'https://images.unsplash.com/photo-1497366811353-6870744d04b2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['room_id'], ['name', 'capacity', 'location', 'price', 'status', 'image', 'created_at', 'updated_at']);

        DB::table('equipments')->upsert([
            ['equipment_id' => 1, 'name' => 'Máy chiếu Full HD', 'created_at' => $now, 'updated_at' => $now],
            ['equipment_id' => 2, 'name' => 'Loa Bluetooth Marshall', 'created_at' => $now, 'updated_at' => $now],
            ['equipment_id' => 3, 'name' => 'Bảng tương tác thông minh', 'created_at' => $now, 'updated_at' => $now],
            ['equipment_id' => 4, 'name' => 'Máy điều hòa Inverter', 'created_at' => $now, 'updated_at' => $now],
            ['equipment_id' => 5, 'name' => 'Micro không dây', 'created_at' => $now, 'updated_at' => $now],
        ], ['equipment_id'], ['name', 'created_at', 'updated_at']);

        DB::table('room_equipments')->upsert([
            ['room_id' => 1, 'equipment_id' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['room_id' => 1, 'equipment_id' => 4, 'created_at' => $now, 'updated_at' => $now],
            ['room_id' => 3, 'equipment_id' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['room_id' => 3, 'equipment_id' => 3, 'created_at' => $now, 'updated_at' => $now],
            ['room_id' => 3, 'equipment_id' => 5, 'created_at' => $now, 'updated_at' => $now],
        ], ['room_id', 'equipment_id'], ['created_at', 'updated_at']);

        DB::table('news_categories')->upsert([
            ['news_category_id' => 1, 'name' => 'Kinh nghiệm học tập', 'slug' => 'kinh-nghiem-hoc-tap', 'created_at' => $now, 'updated_at' => $now],
            ['news_category_id' => 2, 'name' => 'Sự kiện trung tâm', 'slug' => 'su-kien-trung-tam', 'created_at' => $now, 'updated_at' => $now],
            ['news_category_id' => 3, 'name' => 'Văn hóa Trung Hoa', 'slug' => 'van-hoa-trung-hoa', 'created_at' => $now, 'updated_at' => $now],
        ], ['news_category_id'], ['name', 'slug', 'created_at', 'updated_at']);

        DB::table('news')->upsert([
            [
                'news_id' => 1,
                'title' => '5 Bí quyết nhớ chữ Hán siêu nhanh',
                'slug' => '5-bi-quyet-nho-chu-han',
                'summary' => 'Làm sao để không quên mặt chữ?',
                'content' => 'Nội dung chi tiết về phương pháp chiết tự...',
                'news_category_id' => 1,
                'author_id' => 1,
                'is_published' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'news_id' => 2,
                'title' => 'Lễ hội Bánh Trôi nước tại Trung tâm',
                'slug' => 'le-hoi-banh-troi-nuoc',
                'summary' => 'Hoạt động ngoại khóa cuối tuần.',
                'content' => 'Học viên cùng nhau làm bánh và học từ vựng...',
                'news_category_id' => 2,
                'author_id' => 2,
                'is_published' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'news_id' => 3,
                'title' => 'Du lịch Cần Thơ - Trung Quốc: Những điều cần biết',
                'slug' => 'du-lich-can-tho-trung-quoc',
                'summary' => 'Hướng dẫn xin visa du học và du lịch.',
                'content' => 'Các thủ tục cần thiết khi bay từ Cần Thơ...',
                'news_category_id' => 3,
                'author_id' => 4,
                'is_published' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'news_id' => 4,
                'title' => 'Ưu đãi học phí hè 2026',
                'slug' => 'uu-dai-hoc-phi-he-2026',
                'summary' => 'Giảm ngay 20% cho nhóm 3 người.',
                'content' => 'Chương trình áp dụng từ tháng 5 đến tháng 8...',
                'news_category_id' => 2,
                'author_id' => 1,
                'is_published' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'news_id' => 5,
                'title' => 'Phân biệt HSK và TOCFL',
                'slug' => 'phan-biet-hsk-va-tocfl',
                'summary' => 'Bạn nên thi chứng chỉ nào?',
                'content' => 'So sánh chi tiết về cấu trúc bài thi và giá trị...',
                'news_category_id' => 1,
                'author_id' => 1,
                'is_published' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['news_id'], ['title', 'slug', 'summary', 'content', 'news_category_id', 'author_id', 'is_published', 'created_at', 'updated_at']);

        DB::table('sliders')->upsert([
            [
                'slider_id' => 1,
                'title' => 'Chào mừng đến với Tiếng Trung Cần Thơ',
                'description' => 'Nơi chắp cánh ước mơ chinh phục Hán ngữ.',
                'image_url' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644',
                'link_url' => '/about',
                'position' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slider_id' => 2,
                'title' => 'Khóa học HSK 3 cấp tốc - Cam kết đầu ra',
                'description' => 'Giảm 10% khi đăng ký trước ngày 20/03.',
                'image_url' => 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173',
                'link_url' => '/courses/hsk-3',
                'position' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slider_id' => 3,
                'title' => 'Học tiếng Trung qua bài hát',
                'description' => 'Câu lạc bộ sinh hoạt vào mỗi tối Thứ 7.',
                'image_url' => 'https://images.unsplash.com/photo-1516280440614-37939bbacd81',
                'link_url' => '/news/clb-am-nhac',
                'position' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slider_id' => 4,
                'title' => 'Không gian học tập hiện đại',
                'description' => 'Cơ sở vật chất đạt chuẩn quốc tế.',
                'image_url' => 'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
                'link_url' => '/rooms',
                'position' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slider_id' => 5,
                'title' => 'Đội ngũ giáo viên tâm huyết',
                'description' => 'Giáo viên bản xứ và thạc sĩ chuyên ngành.',
                'image_url' => 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e',
                'link_url' => '/teachers',
                'position' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['slider_id'], ['title', 'description', 'image_url', 'link_url', 'position', 'is_active', 'created_at', 'updated_at']);

        DB::table('course_registrations')->upsert([
            [
                'registration_id' => 1,
                'course_id' => 1,
                'student_name' => 'Nguyễn Văn A',
                'student_email' => 'vana@gmail.com',
                'student_phone' => '0907123456',
                'payment_status' => 'paid',
                'status' => 'confirmed',
                'actual_price' => 2500000,
                'registration_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_id' => 2,
                'course_id' => 2,
                'student_name' => 'Lê Thị B',
                'student_email' => 'thib@gmail.com',
                'student_phone' => '0918777888',
                'payment_status' => 'unpaid',
                'status' => 'pending',
                'actual_price' => 4200000,
                'registration_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_id' => 3,
                'course_id' => 1,
                'student_name' => 'Phạm Thành C',
                'student_email' => 'thanhc@gmail.com',
                'student_phone' => '0939111222',
                'payment_status' => 'paid',
                'status' => 'confirmed',
                'actual_price' => 2500000,
                'registration_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_id' => 4,
                'course_id' => 3,
                'student_name' => 'Hoàng Văn D',
                'student_email' => 'vand@gmail.com',
                'student_phone' => '0949333444',
                'payment_status' => 'refunded',
                'status' => 'cancelled',
                'actual_price' => 5500000,
                'registration_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'registration_id' => 5,
                'course_id' => 5,
                'student_name' => 'Đặng Thị E',
                'student_email' => 'thie@gmail.com',
                'student_phone' => '0988555666',
                'payment_status' => 'paid',
                'status' => 'completed',
                'actual_price' => 8000000,
                'registration_date' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ], ['registration_id'], ['course_id', 'student_name', 'student_email', 'student_phone', 'payment_status', 'status', 'actual_price', 'registration_date', 'created_at', 'updated_at']);
    }
}
